services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "127.0.0.1:6333:6333"
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_SERVICE_API_KEY}
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: